---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: canaries.flagger.app
  annotations:
    helm.sh/resource-policy: keep
spec:
  group: flagger.app
  version: v1alpha3
  versions:
    - name: v1alpha3
      served: true
      storage: true
    - name: v1alpha2
      served: true
      storage: false
    - name: v1alpha1
      served: true
      storage: false
  names:
    plural: canaries
    singular: canary
    kind: Canary
    categories:
      - all
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Status
      type: string
      JSONPath: .status.phase
    - name: Weight
      type: string
      JSONPath: .status.canaryWeight
    - name: LastTransitionTime
      type: string
      JSONPath: .status.lastTransitionTime
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - targetRef
            - service
            - canaryAnalysis
          properties:
            progressDeadlineSeconds:
              type: number
            targetRef:
              type: object
              required: ['apiVersion', 'kind', 'name']
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
            autoscalerRef:
              anyOf:
                - type: string
                - type: object
              required: ['apiVersion', 'kind', 'name']
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
            ingressRef:
              anyOf:
                - type: string
                - type: object
              required: ['apiVersion', 'kind', 'name']
              properties:
                apiVersion:
                  type: string
                kind:
                  type: string
                name:
                  type: string
            service:
              type: object
              required: ['port']
              properties:
                port:
                  type: number
                portName:
                  type: string
                meshName:
                  type: string
                timeout:
                  type: string
            skipAnalysis:
              type: boolean
            canaryAnalysis:
              properties:
                interval:
                  type: string
                  pattern: "^[0-9]+(m|s)"
                iterations:
                  type: number
                threshold:
                  type: number
                maxWeight:
                  type: number
                stepWeight:
                  type: number
                metrics:
                  type: array
                  properties:
                    items:
                      type: object
                      required: ['name', 'threshold']
                      properties:
                        name:
                          type: string
                        interval:
                          type: string
                          pattern: "^[0-9]+(m|s)"
                        threshold:
                          type: number
                        query:
                          type: string
                webhooks:
                  type: array
                  properties:
                    items:
                      type: object
                      required: ['name', 'url', 'timeout']
                      properties:
                        name:
                          type: string
                        type:
                          type: string
                          enum:
                            - ""
                            - pre-rollout
                            - rollout
                            - post-rollout
                        url:
                          type: string
                          format: url
                        timeout:
                          type: string
                          pattern: "^[0-9]+(m|s)"
        status:
          properties:
            phase:
              type: string
              enum:
                - ""
                - Initialized
                - Progressing
                - Succeeded
                - Failed
            canaryWeight:
              type: number
            failedChecks:
              type: number
            iterations:
              type: number
            lastAppliedSpec:
              type: string
            lastTransitionTime:
              type: string
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flagger
  namespace: istio-system
  labels:
    app: flagger
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: flagger
  labels:
    app: flagger
rules:
  - apiGroups:
      - ""
    resources:
      - events
      - configmaps
      - secrets
      - services
    verbs: ["*"]
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs: ["*"]
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs: ["*"]
  - apiGroups:
      - "extensions"
    resources:
      - ingresses
      - ingresses/status
    verbs: ["*"]
  - apiGroups:
      - flagger.app
    resources:
      - canaries
      - canaries/status
    verbs: ["*"]
  - apiGroups:
      - networking.istio.io
    resources:
      - virtualservices
      - virtualservices/status
    verbs: ["*"]
  - apiGroups:
      - appmesh.k8s.aws
    resources:
      - meshes
      - meshes/status
      - virtualnodes
      - virtualnodes/status
      - virtualservices
      - virtualservices/status
    verbs: ["*"]
  - apiGroups:
      - split.smi-spec.io
    resources:
      - trafficsplits
    verbs: ["*"]
  - nonResourceURLs:
      - /version
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: flagger
  labels:
    app: flagger
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: flagger
subjects:
- kind: ServiceAccount
  name: flagger
  namespace: istio-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagger
  namespace: istio-system
  labels:
    app: flagger
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: flagger
  template:
    metadata:
      labels:
        app: flagger
      annotations:
        prometheus.io/scrape: "true"
    spec:
      serviceAccountName: flagger
      containers:
      - name: flagger
        image: weaveworks/flagger:master-12d84b2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
        command:
        - ./flagger
        - -log-level=info
        - -control-loop-interval=10s
        - -mesh-provider=smi:istio
        - -metrics-server=http://prometheus.istio-system.svc.cluster.local:9090
        livenessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=2
            - --spider
            - http://localhost:8080/healthz
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - wget
            - --quiet
            - --tries=1
            - --timeout=2
            - --spider
            - http://localhost:8080/healthz
          timeoutSeconds: 5
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "32Mi"
            cpu: "10m"
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
