---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
    version: v1
spec:
  selector:
    matchLabels:
      app: reviews
      version: v1
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: reviews
        version: v1
    spec:
      containers:
      - name: reviews
        image: istio/examples-bookinfo-reviews-v1:1.10.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
