version: 2
jobs:
  test:
    docker:
      - image: golang:1.12.7
    working_directory: /go/src/github.com/deislabs/smi-adapter-istio
    steps:
      - checkout
      - run: make bootstrap
      - run: make test

  build:
    docker:
      - image: golang:1.12.7
    working_directory: /go/src/github.com/deislabs/smi-adapter-istio
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: build and push image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS && \
              make build push
workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - build:
          requires:
          - test
          filters:
            branches:
              only: master
