apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: traffictargets.access.smi-spec.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.service
    description: The service
    name: Service
    type: string
  group: access.smi-spec.io
  names:
    kind: TrafficTarget
    listKind: TrafficTargetList
    plural: traffictargets
    singular: traffictarget
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
