apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: httproutegroups.specs.smi-spec.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.service
    description: The service
    name: Service
    type: string
  group: specs.smi-spec.io
  names:
    kind: HTTPRouteGroup
    listKind: HTTPRouteGroupList
    plural: httproutegroups
    singular: httproutegroup
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
