apiVersion: apps/v1
kind: Deployment
metadata:
  name: smi-adapter-istio
  namespace: istio-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: smi-adapter-istio
  template:
    metadata:
      labels:
        name: smi-adapter-istio
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: smi-adapter-istio
      containers:
        - name: smi-adapter-istio
          image: quay.io/kinvolk/smi-adapter-istio:c7f8456
          command:
          - smi-adapter-istio
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "smi-adapter-istio"
