kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: smi-adapter-istio
subjects:
- kind: ServiceAccount
  name: smi-adapter-istio
roleRef:
  kind: Role
  name: smi-adapter-istio
  apiGroup: rbac.authorization.k8s.io
